name: card_scanner
description: Fast, Accurate and Secure Credit & Debit card scanning library for flutter.
version: 1.0.4
homepage: https://github.com/nateshmbhat/card-scanner-flutter
repository: https://github.com/nateshmbhat/card-scanner-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
 plugin:
    platforms:
      android:
        package: com.nateshmbhat.card_scanner
        pluginClass: CardScannerPlugin
      ios:
        pluginClass: CardScannerPlugin
